# 1. 라이브러리 호출, Raw데이터 불러오기

In [1]:
import pandas as pd 
import numpy as np

raw = pd.read_csv('C:/Data_Engineer_Study/멀캠_PJT_1/Data_set/New_Data/상권 매출데이터/19년도_매출 데이터(자치구, 동추가).csv', encoding = 'cp949')
sub = pd.read_csv('C:/Data_Engineer_Study/멀캠_PJT_1/Data_set/Raw_Data/서울 지하철역 승하차 인원/1~8호선승하차인원_2023년.csv', encoding = 'cp949')

## 상권 매출데이터에서 '~~역'이 들어가는 '상권코드명' 추출
- raw : 상권매출 데이터
- sub : 지하철 유동인구 데이터

In [2]:
raw.head(1)

,Unnamed: 0,기준_년_코드,기준_분기_코드,상권_구분_코드,상권_구분_코드_명,상권_코드,자치구,동,상권_코드_명,서비스_업종_코드,...,시간대_건수~24_매출_건수,남성_매출_건수,여성_매출_건수,연령대_10_매출_건수,연령대_20_매출_건수,연령대_30_매출_건수,연령대_40_매출_건수,연령대_50_매출_건수,연령대_60_이상_매출_건수,점포수
0,0,2019,1,A,골목상권,2110001,종로구,평창동,이북5도청사,CS100001,...,382,13204,6513,35,864,1963,4440,6123,6287,25

In [3]:
sub.head(1)

,연번,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
0,1,2023-01-01,1호선,150,서울역,승차,215,145,231,594,...,2655,2509,2696,2549,2462,2177,2190,1808,734,7

- raw 의 '상권_코드_명' 컬럼중 지하철역 추출
- raw 의 '상권_코드_명' -> raw_code

In [4]:
raw_code = raw[['상권_코드_명']]

In [5]:
raw_code

            상권_코드_명
0            이북5도청사
1            이북5도청사
2            이북5도청사
3            이북5도청사
4            이북5도청사
...             ...
147967  강남 마이스 관광특구
147968  강남 마이스 관광특구
147969  강남 마이스 관광특구
147970  강남 마이스 관광특구
147971  강남 마이스 관광특구

[147972 rows x 1 columns]

~ 역 포함한 행만 추출

In [6]:
# ~~역이 포함된 행 추출
raw_code = raw_code[raw_code['상권_코드_명'].str.contains('역')]

중복되는 행 제거

In [7]:
# 중복 행 제거 
raw_code.drop_duplicates(inplace=True)

C:\Users\yju12\AppData\Local\Temp\ipykernel_9408\1151558791.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_code.drop_duplicates(inplace=True)

In [8]:
raw_code.reset_index(drop = True, inplace = True)

## 'OO역' 뒤 필요없는 부분 제거

In [9]:
raw_code.tail(10)

            상권_코드_명
532        쌍문역둘리상점가
533   쌍문시장(쌍문역골목시장)
534        쌍문역동측상점가
535          창동역상점가
536          역촌중앙시장
537     선유도역 골목형상점가
538      영등포역지하도상점가
539         남성역골목시장
540         둔촌역전통시장
541  강남터미널지하도상점가2구역

In [10]:
# 공백을 기준으로 나누어도 크게 정제될거같진 않음
raw_code['상권_코드_명'].str.split(' ')

0            [독립문역, 1번]
1           [종로5가역, 4번]
2             [혜화역, 1번]
3            [동대문역, 1번]
4            [동대문역, 3번]
             ...
537      [선유도역, 골목형상점가]
538        [영등포역지하도상점가]
539           [남성역골목시장]
540           [둔촌역전통시장]
541    [강남터미널지하도상점가2구역]
Name: 상권_코드_명, Length: 542, dtype: object

In [11]:
raw_code['상권_코드_명'] = raw_code['상권_코드_명'].str.replace('역.*', '역', regex = True)

# replace('역.*', '역', regex=True) : '둔촌역전통시장'인 경우 '역'~끝까지의 단어 '역전통시장'을 '역'으로 변경, 정규표현식(.*) 사용을 위해 regex = True

# 나중에 찾은건데 '역촌중앙시장'이 '역'만 남게되었음...

C:\Users\yju12\AppData\Local\Temp\ipykernel_9408\4101785921.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_code['상권_코드_명'] = raw_code['상권_코드_명'].str.replace('역.*', '역', regex = True)

In [12]:
raw_code
# 강남터미널지하도상점가2구역 -> 제거해야함

            상권_코드_명
0              독립문역
1             종로5가역
2               혜화역
3              동대문역
4              동대문역
..              ...
537            선유도역
538            영등포역
539             남성역
540             둔촌역
541  강남터미널지하도상점가2구역

[542 rows x 1 columns]

In [13]:
# 글자길이가 대략 7글자 넘어가면 의심스러울듯해서 확인했으나 7글자 넘어도 정상적인 역이 많음
# 괄호 ( 가 붙어있는 데이터 앞부분을 지워야 깔끔할 듯 함.
raw_code[raw_code['상권_코드_명'].str.len() >= 7]

            상권_코드_명
43          어린이대공원역
44          어린이대공원역
82          북한산보국문역
83          북한산보국문역
86          성신여대입구역
88          성신여대입구역
90          성신여대입구역
109       4.19민주묘지역
161        경의중앙 신촌역
235        가산디지털단지역
237      서울축산농협 독산역
246     대림차이나타운(대림역
250        구로디지털단지역
269         신대방삼거리역
270         신대방삼거리역
272         신대방삼거리역
348       문현중학교(장지역
356      강동구청(강동구청역
372         서촌(경복궁역
377         대학로(혜화역
383         북창동(시청역
393      용산전자상가(용산역
398        이태원(이태원역
405         어린이대공원역
434        이화여대(이대역
436         월드컵경기장역
456        구로디지털단지역
466         신대방삼거리역
476    고속터미널(고속터미널역
485         양재시민의숲역
494         압구정로데오역
498        강남구청(청담역
510       송파사거리(송파역
533        쌍문시장(쌍문역
541  강남터미널지하도상점가2구역

## 괄호 '(' 앞의 값 제거

In [14]:
# '(' 가 섞인 행 추출
raw_code[raw_code['상권_코드_명'].str.contains('\(')]

          상권_코드_명
246   대림차이나타운(대림역
348     문현중학교(장지역
356    강동구청(강동구청역
372       서촌(경복궁역
375        북촌(안국역
377       대학로(혜화역
383       북창동(시청역
393    용산전자상가(용산역
398      이태원(이태원역
434      이화여대(이대역
476  고속터미널(고속터미널역
498      강남구청(청담역
510     송파사거리(송파역
533      쌍문시장(쌍문역

In [15]:
raw_code['상권_코드_명'] = raw_code['상권_코드_명'].str.split('\(').str[-1]
# str.split('\(').str[-1] '('를 기준으로 나누고 그중 마지막(-1)만을 raw_code['상권_코드_명']데이터로 받는다.

C:\Users\yju12\AppData\Local\Temp\ipykernel_9408\94425275.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_code['상권_코드_명'] = raw_code['상권_코드_명'].str.split('\(').str[-1]

In [16]:
# 제거 확인
raw_code['상권_코드_명'][[434,498,510,533]]

434    이대역
498    청담역
510    송파역
533    쌍문역
Name: 상권_코드_명, dtype: object

In [17]:
raw_code

            상권_코드_명
0              독립문역
1             종로5가역
2               혜화역
3              동대문역
4              동대문역
..              ...
537            선유도역
538            영등포역
539             남성역
540             둔촌역
541  강남터미널지하도상점가2구역

[542 rows x 1 columns]

In [18]:
# 공백이 있는 행 확인
raw_code[raw_code['상권_코드_명'].str.contains(" ")]

        상권_코드_명
161    경의중앙 신촌역
237  서울축산농협 독산역

In [19]:
# 공백기준 문자열 분리 후 str[-1]로 마지막 부분'독산역'선택
raw_code['상권_코드_명'] = raw_code['상권_코드_명'].str.split().str[-1]

C:\Users\yju12\AppData\Local\Temp\ipykernel_9408\2501750495.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_code['상권_코드_명'] = raw_code['상권_코드_명'].str.split().str[-1]

In [20]:
# 중복행 제거
raw_code.drop_duplicates(inplace=True)

C:\Users\yju12\AppData\Local\Temp\ipykernel_9408\2742712783.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  raw_code.drop_duplicates(inplace=True)

In [21]:
pd.set_option('display.max_row', 600)
raw_code
# 역(역촌중앙시장), 구역(구역삼세무서) 제거

            상권_코드_명
0              독립문역
1             종로5가역
2               혜화역
3              동대문역
5               창신역
7              동묘앞역
9              신설동역
10              회현역
12              약수역
13              청구역
15              신당역
16           효창공원앞역
19              서울역
20              남영역
21             삼각지역
23            숙대입구역
25             서빙고역
26             이태원역
27             한강진역
28              옥수역
29             신금호역
30            상왕십리역
31              행당역
33             왕십리역
34             한양대역
35              마장역
37              뚝섬역
38             서울숲역
39             답십리역
40            건대입구역
42           뚝섬유원지역
43          어린이대공원역
45              군자역
46              구의역
47              중곡역
49             아차산역
51             광나루역
53             제기동역
55             고려대역
57              회기역
58             외대앞역
61              중랑역
64              먹골역
65              중화역
68             화랑대역
69              상봉역
71             사가정역
72              면목역
77              망우역
79              신내역
81           한성대입구역
82          북한산보국문역
85              정릉역
86          성신여대입구역
89              보문역
93              길음역
96              안암역
98             상월곡역
99              월곡역
102            돌곶이역
106             석계역
107          북한산우이역
108           솔밭공원역
109       4.19민주묘지역
110             화계역
111            가오리역
112          삼양사거리역
115             미아역
117             수유역
118          미아사거리역
120             쌍문역
121             방학역
122            도봉산역
123             도봉역
124             창동역
127            수락산역
128             월계역
129            광운대역
131             노원역
133             상계역
134             공릉역
135           태릉입구역
136            당고개역
138             수색역
139             증산역
141             새절역
142               역
143             응암역
144             구산역
146            연신내역
155             불광역
159             가좌역
161             신촌역
162             홍제역
165             아현역
167            충정로역
169           마포구청역
172             합정역
174             망원역
175             상수역
177           홍대입구역
178            광흥창역
180            서강대역
182             대흥역
184             마포역
185             이대역
187            애오개역
189          신정네거리역
190             신정역
193             등촌역
194             목동역
195            신목동역
196             송정역
197           공항시장역
198             방화역
199            개화산역
204            신방화역
207            우장산역
208             화곡역
209           양천향교역
213            까치산역
214             발산역
219             가양역
222             염창역
223             온수역
226             천왕역
227            오류동역
230             개봉역
231            남구로역
234             대림역
235        가산디지털단지역
236             독산역
238           금천구청역
239             석수역
240             양평역
241            선유도역
243          영등포구청역
244             문래역
249             당산역
250        구로디지털단지역
251          영등포시장역
255             신풍역
256            영등포역
260             신길역
262            보라매역
264             대방역
266            신대방역
269         신대방삼거리역
273           장승배기역
274            노량진역
276             상도역
279          숭실대입구역
281             남성역
282             이수역
283             사당역
287             신림역
290             봉천역
293          서울대입구역
294            낙성대역
298            구반포역
299            남태령역
300             내방역
303             방배역
308             잠원역
309          남부터미널역
310             양재역
311          청계산입구역
312             논현역
313             언주역
319           강남구청역
320            선정릉역
322             매봉역
323           삼성중앙역
324             청담역
327            봉은사역
328             삼전역
331           석촌고분역
334             석촌역
335           잠실나루역
337           송파나루역
340             송파역
342           한성백제역
343             방이역
344             문정역
345           경찰병원역
348             장지역
349             오금역
352             거여역
354             마천역
355             천호역
356           강동구청역
358             암사역
360             강동역
363            둔촌동역
365           굽은다리역
367             명일역
371            서대문역
372            경복궁역
373            광화문역
374             종각역
375             안국역
376           종로3가역
381             시청역
385          을지로입구역
386             명동역
387          을지로3가역
388            충무로역
389          을지로4가역
393             용산역
394            신용산역
399             금호역
403             성수역
409             강변역
411            청량리역
413            장한평역
423             마들역
429            구파발역
436         월드컵경기장역
442             공덕역
446            오목교역
447           김포공항역
449             마곡역
454             구로역
455            신도림역
464          국회의사당역
465            여의도역
469          총신대입구역
476          고속터미널역
477             서초역
478             교대역
482            신논현역
483             신사역
485         양재시민의숲역
488            압구정역
489             강남역
490             학동역
493              구역
494         압구정로데오역
499             선릉역
500             한티역
502             대치역
504             삼성역
505             수서역
506           잠실새내역
508             잠실역
512           몽촌토성역
513           가락시장역
519             개롱역
524             둔촌역
525             길동역
528             고덕역
541  강남터미널지하도상점가2구역

In [22]:
raw_code = raw_code.drop([142, 493, 541])

In [23]:
raw_code.reset_index(drop = True)

       상권_코드_명
0         독립문역
1        종로5가역
2          혜화역
3         동대문역
4          창신역
5         동묘앞역
6         신설동역
7          회현역
8          약수역
9          청구역
10         신당역
11      효창공원앞역
12         서울역
13         남영역
14        삼각지역
15       숙대입구역
16        서빙고역
17        이태원역
18        한강진역
19         옥수역
20        신금호역
21       상왕십리역
22         행당역
23        왕십리역
24        한양대역
25         마장역
26         뚝섬역
27        서울숲역
28        답십리역
29       건대입구역
30      뚝섬유원지역
31     어린이대공원역
32         군자역
33         구의역
34         중곡역
35        아차산역
36        광나루역
37        제기동역
38        고려대역
39         회기역
40        외대앞역
41         중랑역
42         먹골역
43         중화역
44        화랑대역
45         상봉역
46        사가정역
47         면목역
48         망우역
49         신내역
50      한성대입구역
51     북한산보국문역
52         정릉역
53     성신여대입구역
54         보문역
55         길음역
56         안암역
57        상월곡역
58         월곡역
59        돌곶이역
60         석계역
61      북한산우이역
62       솔밭공원역
63   4.19민주묘지역
64         화계역
65        가오리역
66      삼양사거리역
67         미아역
68         수유역
69      미아사거리역
70         쌍문역
71         방학역
72        도봉산역
73         도봉역
74         창동역
75        수락산역
76         월계역
77        광운대역
78         노원역
79         상계역
80         공릉역
81       태릉입구역
82        당고개역
83         수색역
84         증산역
85         새절역
86         응암역
87         구산역
88        연신내역
89         불광역
90         가좌역
91         신촌역
92         홍제역
93         아현역
94        충정로역
95       마포구청역
96         합정역
97         망원역
98         상수역
99       홍대입구역
100       광흥창역
101       서강대역
102        대흥역
103        마포역
104        이대역
105       애오개역
106     신정네거리역
107        신정역
108        등촌역
109        목동역
110       신목동역
111        송정역
112      공항시장역
113        방화역
114       개화산역
115       신방화역
116       우장산역
117        화곡역
118      양천향교역
119       까치산역
120        발산역
121        가양역
122        염창역
123        온수역
124        천왕역
125       오류동역
126        개봉역
127       남구로역
128        대림역
129   가산디지털단지역
130        독산역
131      금천구청역
132        석수역
133        양평역
134       선유도역
135     영등포구청역
136        문래역
137        당산역
138   구로디지털단지역
139     영등포시장역
140        신풍역
141       영등포역
142        신길역
143       보라매역
144        대방역
145       신대방역
146    신대방삼거리역
147      장승배기역
148       노량진역
149        상도역
150     숭실대입구역
151        남성역
152        이수역
153        사당역
154        신림역
155        봉천역
156     서울대입구역
157       낙성대역
158       구반포역
159       남태령역
160        내방역
161        방배역
162        잠원역
163     남부터미널역
164        양재역
165     청계산입구역
166        논현역
167        언주역
168      강남구청역
169       선정릉역
170        매봉역
171      삼성중앙역
172        청담역
173       봉은사역
174        삼전역
175      석촌고분역
176        석촌역
177      잠실나루역
178      송파나루역
179        송파역
180      한성백제역
181        방이역
182        문정역
183      경찰병원역
184        장지역
185        오금역
186        거여역
187        마천역
188        천호역
189      강동구청역
190        암사역
191        강동역
192       둔촌동역
193      굽은다리역
194        명일역
195       서대문역
196       경복궁역
197       광화문역
198        종각역
199        안국역
200      종로3가역
201        시청역
202     을지로입구역
203        명동역
204     을지로3가역
205       충무로역
206     을지로4가역
207        용산역
208       신용산역
209        금호역
210        성수역
211        강변역
212       청량리역
213       장한평역
214        마들역
215       구파발역
216    월드컵경기장역
217        공덕역
218       오목교역
219      김포공항역
220        마곡역
221        구로역
222       신도림역
223     국회의사당역
224       여의도역
225     총신대입구역
226     고속터미널역
227        서초역
228        교대역
229       신논현역
230        신사역
231    양재시민의숲역
232       압구정역
233        강남역
234        학동역
235    압구정로데오역
236        선릉역
237        한티역
238        대치역
239        삼성역
240        수서역
241      잠실새내역
242        잠실역
243      몽촌토성역
244      가락시장역
245        개롱역
246        둔촌역
247        길동역
248        고덕역

# 지하철 유동인구 전처리

- 지하철 유동인구 데이터(sub) 확인

In [24]:
sub.head()

,연번,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
0,1,2023-01-01,1호선,150,서울역,승차,215,145,231,594,...,2655,2509,2696,2549,2462,2177,2190,1808,734,7
1,2,2023-01-01,1호선,150,서울역,하차,154,636,595,939,...,2282,2295,2526,1930,1897,1487,991,609,280,46
2,3,2023-01-01,1호선,151,시청,승차,48,73,106,194,...,843,895,959,985,670,630,515,330,146,0
3,4,2023-01-01,1호선,151,시청,하차,64,247,293,463,...,602,575,533,456,285,267,246,154,79,18
4,5,2023-01-01,1호선,152,종각,승차,407,235,158,201,...,1145,1402,1223,1272,911,913,906,602,232,3

In [25]:
# 서울역 제외 모든 역 이름이 ~~'역' 이라는 단어가 빠져있음. 
# 괄호 내부 내용 제거 필요
sub['역명'].unique()

array(['서울역', '시청', '종각', '종로3가', '종로5가', '동대문', '신설동', '제기동',
       '청량리(서울시립대입구)', '동묘앞', '을지로입구', '을지로3가', '을지로4가', '동대문역사문화공원(DDP)',
       '신당', '상왕십리', '왕십리(성동구청)', '한양대', '뚝섬', '성수', '건대입구', '구의(광진구청)',
       '강변(동서울터미널)', '잠실나루', '잠실(송파구청)', '잠실새내', '종합운동장', '삼성(무역센터)',
       '선릉', '역삼', '강남', '교대(법원.검찰청)', '서초', '방배', '사당', '낙성대(강감찬)',
       '서울대입구(관악구청)', '봉천', '신림', '신대방', '구로디지털단지', '대림(구로구청)', '신도림',
       '문래', '영등포구청', '당산', '합정', '홍대입구', '신촌', '이대', '아현', '충정로(경기대입구)',
       '용답', '신답', '도림천', '양천구청', '신정네거리', '용두(동대문구청)', '지축', '구파발',
       '연신내', '불광', '녹번', '홍제', '무악재', '독립문', '경복궁(정부서울청사)', '안국', '동대입구',
       '약수', '금호', '옥수', '압구정', '신사', '잠원', '고속터미널', '남부터미널(예술의전당)',
       '양재(서초구청)', '매봉', '도곡', '대치', '학여울', '대청', '일원', '수서', '가락시장',
       '경찰병원', '오금', '당고개', '상계', '노원', '창동', '쌍문', '수유(강북구청)',
       '미아(서울사이버대학)', '미아사거리', '길음', '성신여대입구(돈암)', '한성대입구(삼선교)', '혜화',
       '충무로', '명동', '회현(남대문시장)', '숙대입구(갈월)', '삼각지', '신용산', '이촌(국립중앙박물관)',
       '동작(현충원)', '총신대입구(이수)', '남태령', '방화', '개화산', '김포공항', '송정', '마곡',
       '발산', '우장산', '화곡', '까치산', '신정(은행정)', '목동', '오목교(목동운동장앞)', '양평',
       '영등포시장', '신길', '여의도', '여의나루', '마포', '공덕', '애오개', '서대문',
       '광화문(세종문화회관)', '청구', '신금호', '행당', '마장', '답십리', '장한평', '군자(능동)',
       '아차산(어린이대공원후문)', '광나루(장신대)', '천호(풍납토성)', '강동', '길동',
       '굽은다리(강동구민회관앞)', '명일', '고덕', '상일동', '둔촌동', '올림픽공원(한국체대)', '방이',
       '개롱', '거여', '마천', '강일', '미사', '하남풍산', '하남시청(덕풍·신장)', '하남검단산', '응암',
       '역촌', '독바위', '구산', '새절(신사)', '증산(명지대앞)', '디지털미디어시티', '월드컵경기장(성산)',
       '마포구청', '망원', '상수', '광흥창(서강)', '대흥(서강대앞)', '효창공원앞', '녹사평(용산구청)',
       '이태원', '한강진', '버티고개', '창신', '보문', '안암(고대병원앞)', '고려대(종암)',
       '월곡(동덕여대)', '상월곡(한국과학기술연구원)', '돌곶이', '석계', '태릉입구', '화랑대(서울여대입구)',
       '봉화산(서울의료원)', '장암', '도봉산', '수락산', '마들', '중계', '하계', '공릉(서울과학기술대)',
       '먹골', '중화', '상봉(시외버스터미널)', '면목', '사가정', '용마산(용마폭포공원)', '중곡',
       '어린이대공원(세종대)', '뚝섬유원지', '청담', '강남구청', '학동', '논현', '반포', '내방', '이수',
       '남성', '숭실대입구(살피재)', '상도', '장승배기', '신대방삼거리', '보라매', '신풍', '남구로',
       '가산디지털단지', '철산', '광명사거리', '천왕', '온수(성공회대입구)', '암사', '강동구청',
       '몽촌토성(평화의문)', '석촌', '송파', '문정', '장지', '복정', '산성',
       '남한산성입구(성남법원.검찰청)', '단대오거리', '신흥', '수진', '모란', '남위례'], dtype=object)

In [26]:
sub['역명'] = sub['역명'].str.replace('\(.*\)', '', regex=True)

In [27]:
sub['역명'].unique()

array(['서울역', '시청', '종각', '종로3가', '종로5가', '동대문', '신설동', '제기동', '청량리',
       '동묘앞', '을지로입구', '을지로3가', '을지로4가', '동대문역사문화공원', '신당', '상왕십리', '왕십리',
       '한양대', '뚝섬', '성수', '건대입구', '구의', '강변', '잠실나루', '잠실', '잠실새내',
       '종합운동장', '삼성', '선릉', '역삼', '강남', '교대', '서초', '방배', '사당', '낙성대',
       '서울대입구', '봉천', '신림', '신대방', '구로디지털단지', '대림', '신도림', '문래', '영등포구청',
       '당산', '합정', '홍대입구', '신촌', '이대', '아현', '충정로', '용답', '신답', '도림천',
       '양천구청', '신정네거리', '용두', '지축', '구파발', '연신내', '불광', '녹번', '홍제', '무악재',
       '독립문', '경복궁', '안국', '동대입구', '약수', '금호', '옥수', '압구정', '신사', '잠원',
       '고속터미널', '남부터미널', '양재', '매봉', '도곡', '대치', '학여울', '대청', '일원', '수서',
       '가락시장', '경찰병원', '오금', '당고개', '상계', '노원', '창동', '쌍문', '수유', '미아',
       '미아사거리', '길음', '성신여대입구', '한성대입구', '혜화', '충무로', '명동', '회현', '숙대입구',
       '삼각지', '신용산', '이촌', '동작', '총신대입구', '남태령', '방화', '개화산', '김포공항',
       '송정', '마곡', '발산', '우장산', '화곡', '까치산', '신정', '목동', '오목교', '양평',
       '영등포시장', '신길', '여의도', '여의나루', '마포', '공덕', '애오개', '서대문', '광화문',
       '청구', '신금호', '행당', '마장', '답십리', '장한평', '군자', '아차산', '광나루', '천호',
       '강동', '길동', '굽은다리', '명일', '고덕', '상일동', '둔촌동', '올림픽공원', '방이', '개롱',
       '거여', '마천', '강일', '미사', '하남풍산', '하남시청', '하남검단산', '응암', '역촌', '독바위',
       '구산', '새절', '증산', '디지털미디어시티', '월드컵경기장', '마포구청', '망원', '상수', '광흥창',
       '대흥', '효창공원앞', '녹사평', '이태원', '한강진', '버티고개', '창신', '보문', '안암',
       '고려대', '월곡', '상월곡', '돌곶이', '석계', '태릉입구', '화랑대', '봉화산', '장암', '도봉산',
       '수락산', '마들', '중계', '하계', '공릉', '먹골', '중화', '상봉', '면목', '사가정',
       '용마산', '중곡', '어린이대공원', '뚝섬유원지', '청담', '강남구청', '학동', '논현', '반포',
       '내방', '이수', '남성', '숭실대입구', '상도', '장승배기', '신대방삼거리', '보라매', '신풍',
       '남구로', '가산디지털단지', '철산', '광명사거리', '천왕', '온수', '암사', '강동구청', '몽촌토성',
       '석촌', '송파', '문정', '장지', '복정', '산성', '남한산성입구', '단대오거리', '신흥', '수진',
       '모란', '남위례'], dtype=object)

In [28]:
raw_code['상권_코드_명'] = raw_code['상권_코드_명'].str.replace('역','')

In [29]:
sub['역명'] = sub['역명'].str.replace('역','')

In [30]:
sub['역명'].unique()

array(['서울', '시청', '종각', '종로3가', '종로5가', '동대문', '신설동', '제기동', '청량리',
       '동묘앞', '을지로입구', '을지로3가', '을지로4가', '동대문사문화공원', '신당', '상왕십리', '왕십리',
       '한양대', '뚝섬', '성수', '건대입구', '구의', '강변', '잠실나루', '잠실', '잠실새내',
       '종합운동장', '삼성', '선릉', '삼', '강남', '교대', '서초', '방배', '사당', '낙성대',
       '서울대입구', '봉천', '신림', '신대방', '구로디지털단지', '대림', '신도림', '문래', '영등포구청',
       '당산', '합정', '홍대입구', '신촌', '이대', '아현', '충정로', '용답', '신답', '도림천',
       '양천구청', '신정네거리', '용두', '지축', '구파발', '연신내', '불광', '녹번', '홍제', '무악재',
       '독립문', '경복궁', '안국', '동대입구', '약수', '금호', '옥수', '압구정', '신사', '잠원',
       '고속터미널', '남부터미널', '양재', '매봉', '도곡', '대치', '학여울', '대청', '일원', '수서',
       '가락시장', '경찰병원', '오금', '당고개', '상계', '노원', '창동', '쌍문', '수유', '미아',
       '미아사거리', '길음', '성신여대입구', '한성대입구', '혜화', '충무로', '명동', '회현', '숙대입구',
       '삼각지', '신용산', '이촌', '동작', '총신대입구', '남태령', '방화', '개화산', '김포공항',
       '송정', '마곡', '발산', '우장산', '화곡', '까치산', '신정', '목동', '오목교', '양평',
       '영등포시장', '신길', '여의도', '여의나루', '마포', '공덕', '애오개', '서대문', '광화문',
       '청구', '신금호', '행당', '마장', '답십리', '장한평', '군자', '아차산', '광나루', '천호',
       '강동', '길동', '굽은다리', '명일', '고덕', '상일동', '둔촌동', '올림픽공원', '방이', '개롱',
       '거여', '마천', '강일', '미사', '하남풍산', '하남시청', '하남검단산', '응암', '촌', '독바위',
       '구산', '새절', '증산', '디지털미디어시티', '월드컵경기장', '마포구청', '망원', '상수', '광흥창',
       '대흥', '효창공원앞', '녹사평', '이태원', '한강진', '버티고개', '창신', '보문', '안암',
       '고려대', '월곡', '상월곡', '돌곶이', '석계', '태릉입구', '화랑대', '봉화산', '장암', '도봉산',
       '수락산', '마들', '중계', '하계', '공릉', '먹골', '중화', '상봉', '면목', '사가정',
       '용마산', '중곡', '어린이대공원', '뚝섬유원지', '청담', '강남구청', '학동', '논현', '반포',
       '내방', '이수', '남성', '숭실대입구', '상도', '장승배기', '신대방삼거리', '보라매', '신풍',
       '남구로', '가산디지털단지', '철산', '광명사거리', '천왕', '온수', '암사', '강동구청', '몽촌토성',
       '석촌', '송파', '문정', '장지', '복정', '산성', '남한산성입구', '단대오거리', '신흥', '수진',
       '모란', '남위례'], dtype=object)

In [31]:
sub2 = sub[sub['역명'].isin(raw_code['상권_코드_명'])]

In [32]:
sub2.head()

,연번,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,15-16시간대,16-17시간대,17-18시간대,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후
0,1,2023-01-01,1호선,150,서울,승차,215,145,231,594,...,2655,2509,2696,2549,2462,2177,2190,1808,734,7
1,2,2023-01-01,1호선,150,서울,하차,154,636,595,939,...,2282,2295,2526,1930,1897,1487,991,609,280,46
2,3,2023-01-01,1호선,151,시청,승차,48,73,106,194,...,843,895,959,985,670,630,515,330,146,0
3,4,2023-01-01,1호선,151,시청,하차,64,247,293,463,...,602,575,533,456,285,267,246,154,79,18
4,5,2023-01-01,1호선,152,종각,승차,407,235,158,201,...,1145,1402,1223,1272,911,913,906,602,232,3

- 승하차 구분의 '하차'만 포함

In [33]:
sub2 = sub2[sub2['승하차구분'] == '하차']

- 시간대 합치기 (0~11 / 11~17 / 17~24)

In [34]:
sub2.columns

Index(['연번', '수송일자', '호선', '역번호', '역명', '승하차구분', '06시이전', '06-07시간대',
       '07-08시간대', '08-09시간대', '09-10시간대', '10-11시간대', '11-12시간대', '12-13시간대',
       '13-14시간대', '14-15시간대', '15-16시간대', '16-17시간대', '17-18시간대', '18-19시간대',
       '19-20시간대', '20-21시간대', '21-22시간대', '22-23시간대', '23-24시간대', '24시이후'],
      dtype='object')

In [35]:
sub2['00~11시'] = sub2['06시이전'] + sub2['06-07시간대'] + sub2['07-08시간대'] + sub2['08-09시간대'] + sub2['09-10시간대'] + sub2['10-11시간대']
sub2['11~17시'] = sub2['11-12시간대'] + sub2['12-13시간대'] + sub2['13-14시간대'] + sub2['14-15시간대'] + sub2['15-16시간대'] + sub2['16-17시간대']
sub2['17~24시'] = sub2['17-18시간대'] + sub2['18-19시간대'] + sub2['19-20시간대'] + sub2['20-21시간대'] + sub2['21-22시간대'] + sub2['22-23시간대'] + sub2['23-24시간대'] + sub2['24시이후']

In [36]:
sub2[['00~11시', '11~17시', '17~24시']]

       00~11시  11~17시  17~24시
1        4954   12324    9766
3        2158    4104    2038
5        2221    6034    2536
7        1683    7153    2062
9        1430    5628    1960
...       ...     ...     ...
65260     999    2993    2535
65262     745    1949    2567
65264     873    1849    2060
65266    1456    3068    2532
65268    1925    4517    4040

[26762 rows x 3 columns]

In [37]:
sub2.head()

,연번,수송일자,호선,역번호,역명,승하차구분,06시이전,06-07시간대,07-08시간대,08-09시간대,...,18-19시간대,19-20시간대,20-21시간대,21-22시간대,22-23시간대,23-24시간대,24시이후,00~11시,11~17시,17~24시
1,2,2023-01-01,1호선,150,서울,하차,154,636,595,939,...,1930,1897,1487,991,609,280,46,4954,12324,9766
3,4,2023-01-01,1호선,151,시청,하차,64,247,293,463,...,456,285,267,246,154,79,18,2158,4104,2038
5,6,2023-01-01,1호선,152,종각,하차,69,164,268,384,...,564,391,267,207,149,136,15,2221,6034,2536
7,8,2023-01-01,1호선,153,종로3가,하차,39,118,130,274,...,454,316,227,201,122,90,31,1683,7153,2062
9,10,2023-01-01,1호선,154,종로5가,하차,26,84,130,216,...,438,304,195,174,152,95,10,1430,5628,1960

In [38]:
raw_code.head()

  상권_코드_명
0     독립문
1    종로5가
2      혜화
3     동대문
5      창신

- 완료된 23년 지하철 하차정보 및 상권매출데이터 역정보 csv저장

In [39]:
sub2.to_csv('23년 서울 지하철 하차인원 정보.csv', index = False, encoding = 'cp949')

In [40]:
raw_code.to_csv('상권매출데이터 역정보추출.csv', index = False , encoding = 'cp949')